
select a.EMPLOYEE_ID, a.EVALUATION_YEAR, a.EVALUATION_MONTH, a.VERSION_ID, sum(a.TOTAL_MARK * b.WEIGHT) as TOTAL_MARK from
(
SELECT 
t.EMPLOYEE_ID, 
t1.POSITION_ID as POSITION_ID, 
t.EVALUATION_FORM_ID,
t.EVALUATION_YEAR,
t.EVALUATION_MONTH, 
t.VERSION_ID,
sum(t.MARK)/t2.FULL_MARK  as TOTAL_MARK 
FROM t_evaluation_results t
join t_employee t1 on t1.ID=t.EMPLOYEE_ID
join v_evaluation_form_full_mark t2 on t2.EVALUATION_FORM_ID=t.EVALUATION_FORM_ID
group by t.EMPLOYEE_ID, t.EVALUATION_FORM_ID, t.EVALUATION_YEAR, t.EVALUATION_MONTH, t.VERSION_ID
) a 
join (select t.WEIGHT, t.POSITION_ID, t.VERSION_ID, t.EVALUATION_FORM_ID from t_position_evaluation_forms t) b on
a.POSITION_ID=b.POSITION_ID and a.VERSION_ID=b.VERSION_ID and a.EVALUATION_FORM_ID=b.EVALUATION_FORM_ID
group by a.EVALUATION_YEAR, a.EVALUATION_MONTH, a.VERSION_ID;
